// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFOQZVrBPyAZRwthX7dvnSCtQLnJ9kp2Q',
    appId: '1:1027562138382:web:4cf6393bdfe0d7b0dd455f',
    messagingSenderId: '1027562138382',
    projectId: 'social-media-177dd',
    authDomain: 'social-media-177dd.firebaseapp.com',
    storageBucket: 'social-media-177dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGG1rKDTXhVnW3yqfFP8PmNjej12tQ8-g',
    appId: '1:1027562138382:android:fefe0e06a05036ecdd455f',
    messagingSenderId: '1027562138382',
    projectId: 'social-media-177dd',
    storageBucket: 'social-media-177dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7E5mF8zFjSRHpzmR1vZq9lHR-wFRIpI0',
    appId: '1:1027562138382:ios:aa8a88ad0d62776add455f',
    messagingSenderId: '1027562138382',
    projectId: 'social-media-177dd',
    storageBucket: 'social-media-177dd.appspot.com',
    iosBundleId: 'com.kpsoft.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7E5mF8zFjSRHpzmR1vZq9lHR-wFRIpI0',
    appId: '1:1027562138382:ios:aa8a88ad0d62776add455f',
    messagingSenderId: '1027562138382',
    projectId: 'social-media-177dd',
    storageBucket: 'social-media-177dd.appspot.com',
    iosBundleId: 'com.kpsoft.socialmedia',
  );
}
